### ISSUE TITLE
JSDelivr Problems

### ISSUE THREAD

**Issue by sn0w** [sn0w/groupwatch#2] opened 2017-05-21 19:30 UTC
~~It seems like JsDelivr is experiencing some serious load-balancing issues.~~
~~The current plan is to install the dependencies through Bower/Yarn and selfhost them.~~

Edit: Switch postponed. See below.

**Comment by MartinKolarik** [comment] 2017-05-21 20:33
@sn0w would you mind sharing some info regarding the mentioned issues?

**Comment by sn0w** [comment] 2017-05-22 08:15
@MartinKolarik

The affected users are from the UK (West Midlands).
They're getting 504's and/or 502's from time to time.

All test were using SSL to connect to your servers.

I don't know which of your servers were hit by all of their requests though.
The only user that shared an IP reported that `94.31.29.138` is having problems.

Thanks in advance for your help 😃

**Comment by MartinKolarik** [comment] 2017-05-22 11:21
Thanks for the info. This looks like a problem we were investigating 2 days ago and it should be fixed since then.

Do you know if there were any problems in the past two days?

**Comment by sn0w** [comment] 2017-05-22 12:08
Nice to hear.
The problems actually happened two days ago and the system wasn't used in the meantime.
I'll investigate and keep you updated.

By the way:
Do you have any kind of status page where you announce such issues?
Would be nice to have a local failover ready in case something like this happens again.

I only found http://status.jsdelivr.com/ but that's resolving to localhost for some reason.
![](https://i.imgur.com/FvrDa6w.png)

**Comment by MartinKolarik** [comment] 2017-05-22 13:14
We updated our infrastructure recently and the status page got broken in the process. Working on bringing it back but it'll take some time.

**Comment by sn0w** [comment] 2017-05-22 13:34
Ok. Thanks a lot for your help :)

**Comment by sn0w** [comment] 2017-10-15 16:26
@MartinKolarik After your latest infrastructure update any packages with more than 50mb are rejected.
Is there any chance to remove/lift that limit?
This change currently breaks https://www.npmjs.com/package/video.js

**Comment by MartinKolarik** [comment] 2017-10-15 16:43
@sn0w the issue is tracked in videojs/video.js#4609

@jimaek any objections to adding `video.js` to the list of exceptions to make it work immediately? 57 MB shouldn't cause any issues.

**Comment by jimaek** [comment] 2017-10-15 20:04
We could just lift the limit to 60 for everyone

**Comment by MartinKolarik** [comment] 2017-10-20 14:00
I'm going to add video.js to whitelist for now and we can discuss increasing the limit for all packages later.

**Comment by MartinKolarik** [comment] 2017-10-20 14:18
@jimaek deploy when ready

**Comment by jimaek** [comment] 2017-10-20 17:06
Deployed https://cdn.jsdelivr.net/npm/video.js@6.2.8/

**Comment by sn0w** [comment] 2017-10-20 18:00
Awesome, thanks :)

**Closed** 2018-05-04 22:41 UTC
Labels: investigating
